### PR TITLE
simulation now uses data from csv files

### PR DESCRIPTION
**Pull request by john-marinelli**

### CODE REVIEW

**Comment by rdriven** [comment]
Running the app fails because because simulation.py includes high_plains_raceway (that doesn't exist) from track_properties.py 
`from track_properties import (TrackProperties,
                              high_plains_raceway)'
Perhaps comment it out and include simple_track as the default?

**Comment by john-marinelli** [comment]
> 
> 
> Running the app fails because because simulation.py includes high_plains_raceway (that doesn't exist) from track_properties.py
> `from track_properties import (TrackProperties,
> high_plains_raceway)'
> Perhaps comment it out and include simple_track as the default?

I remember this issue and I don't think I ever resolved it. I need to remove air density from the dictionary before iterating over it. Kind of confused as to why the simulation ran on my machine before my pull request

**Comment by john-marinelli** [comment]
Nevermind -- I just left in an import statement that was holding everything up

**Review by rdriven — CHANGES_REQUESTED** [review]
The default simulation runs and code changes are looking good. There is still a few lines in track_properties.py  that could be cleaned up (125:128) that still refer to High Plains, and (137)  is there and commented out - what's it's purpose?

**Review by rdriven — APPROVED** [review]

**Pull request merged**
